name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub variables
        run: |
          echo "Version Number: ${{ vars.VERSION_NUMBER }}"

      - name: curl update
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/notsotraumatiq/To-Do \
          -d '{"name":"VERSION_NUMEBER","value":"octocat"}'
