name: My Workflow

permissions:
  contents: write
  issues: write
on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub variables
        run: |
          echo "Version Number: ${{ vars.VERSION_NUMBER }}"

      - name: curl update
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/notsotraumatiq/To-Do/actions/variables/VERSION_NUMBER \
          -d '{"name":"notsotraumatiq","value":"octocat"}'
