name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub variables
        run: |
          echo "Version Number: ${{ vars.VERSION_NUMBER }}"

      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Test
        run: echo $GITHUB_SHA_SHORT
