name: My Workflow

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub variables
        run: |
          echo "Version Number: ${{ vars.VERSION_NUMBER }}"

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ vars.VERSION_NUMBER }}
          version-fragment: "feature"
      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }}

      - name: curl updates
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/notsotraumatiq/To-Do/actions/variables/VERSION_NUMBER \
          -d '{"name":"VERSION_NUMBER","value":"${{ steps.bump_version.outputs.next-version }}"}'

      - name: Update using gh
        run: |
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/notsotraumatiq/To-Do/actions/variables/VERSION_NUMBER \
          -f name='VERSION_NUMBER' \
          -f value='octocat'
