name: My Workflow

on:
  push:
    branches:
      - master
      - dev

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub variables
        run: |
          echo "Version Number: ${{ vars.VERSION_NUMBER }}"

      - name: curl updates
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/notsotraumatiq/To-Do/actions/variables/VERSION_NUMBER \
          -d '{"name":"VERSION_NUMBER","value":"octocat"}'

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: "2.11.7-alpha.3" # also accepted: 'v2.11.7-alpha.3' | '2.11.7-alpha3'
          version-fragment: "feature"
      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }}
        # will print 2.12.0
