name: My Workflow

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub variables
        run: |
          echo "Version Number: ${{ vars.VERSION_NUMBER }}"

      - name: curl updates
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/notsotraumatiq/To-Do/actions/variables/VERSION_NUMBER \
          -d '{"name":"VERSION_NUMBER","value":"octocat"}'
